### ISSUE TITLE
Mailgun is not opensource friendly

### ISSUE THREAD

**Issue by UralZima** [mailgun/flanker#134]
You released the sources, well, good. But nobody maintenance that. Nobody answer the issues, most of them are unanswered. You have bunch of pull requests which you are not going to merge. 
You loose your reputation. 
If you opted to opensource world, please do it well and keep updated. 
You must understand, that it is more advertising to you, when your github account have activity = more money to you.

Please resolve issues and merge pull requests, and keep things updated.

**Comment by horkhe** [comment]
You are right about everything. For a very long time we have not paid enough... what the heck let's be honest - any attention to most of our open source repositories. I can dive into the reasons why, but that will probably be perceived by the community like whining, so I won't. But we do want to rectify the situation. So in the nearest future we (and I in particular) will be going through all the pending PRs. That does not mean that all of them are going to be accepted, but we will be considering them. I will probably start with updating them asking authors if they are still interested and will proceed with those who responds. You see that the list is long and we will be mostly doing that in our spare time so that might take awhile.
