### ISSUE TITLE
Flanker 0.9.0: No handlers could be found for logger "flanker.addresslib._parser.parser"

### ISSUE THREAD

**Issue by jfly** [mailgun/flanker#197]
(This is tangentially related to https://github.com/mailgun/flanker/issues/196)

I just upgraded to Flanker 0.9.0, and I'm seeing the following warning when importing `address`:

```
(external-api-kWcvfjzK) ➜  ~/honor/external-api git:(unpinning-flanker) pip freeze | grep -i flanker
flanker==0.9.0
(external-api-kWcvfjzK) ➜  ~/honor/external-api git:(unpinning-flanker) ✗ python -c 'from flanker.addresslib import address'
No handlers could be found for logger "flanker.addresslib._parser.parser"
(external-api-kWcvfjzK) ➜  ~/honor/external-api git:(unpinning-flanker) ✗ python -c 'from flanker.addresslib import address'
(external-api-kWcvfjzK) ➜  ~/honor/external-api git:(unpinning-flanker) ✗ python -c 'from flanker.addresslib import address'
(external-api-kWcvfjzK) ➜  ~/honor/external-api git:(unpinning-flanker) ✗ 
```

What's interesting (as you can see above) is that this only seems to have happened on the very first time after I upgraded to Flanker 0.9.0. I haven't dug into why this is. This article: http://excid3.com/blog/no-handlers-could-be-found-for-logger makes it sound like the right fix is to call `logging.basicConfig()` somewhere in your library, and I can see that this commit: https://github.com/mailgun/flanker/commit/16c2ba980efceb153893b41edd6acdce3edb83df#diff-719ec1689e2ef8a5c36379bc155ab071L8 removed an invocation of `logging.basicConfig()`, so that seems like possibly the root cause?

**Comment by horkhe** [comment]
The library is not supposed to configure logger. It is responsibility of an application, hence the call was removed. But I think nothing should be logged as a result of `import` because that makes it is hard to ensure that `logging.basicConfig()`, or something similar, is called before import. I will fix that. Thank you for reporting.

**Comment by horkhe** [comment]
After further review of the issue I realized that the logging triggered by import cannot be avoided, because it comes from `ply` library that we use to compile the parser itself. Note that it only tries to log during import when it rebuilds *parsetab* files, that in turn only happens if the `ply` version in your virtualenv differs from the one used to build the *parsetab* files shipped with Flanker, that is *v3.10*. Besides rebuild happens only the very first time you ran your application. On subsequent runs the rebuild *parsetab* files are already in your virtualenv and won't be rebuilt again, hence no logger warning is going to appear.

So I am closing this as "won't fix".

**Comment by jfly** [comment]
Ahh, I see. Thanks for doing the investigation and the explanation! Should we be reporting this bug upstream to `ply`, then?

**Comment by horkhe** [comment]
It is not really the `ply` issue but how we decided to use it. The **Flanker** initializes parser when it is imported, so it is hard for an application to initialize logger before **Flanker** starts using one. We could have introduced `init` function and make application call it on startup for parser initialization. In that case applications would have a chance to initialize logger in time.

We are not going to introduce `init` function now, so we are stuck with that annoying log line for time being.
